/* GitHub Pages member/admin controller. Configure only this placeholder. */
(function (root) {
  'use strict';
  var APP_CONFIG = root.APP_CONFIG || { apiUrl: 'PASTE_APPS_SCRIPT_EXEC_URL_HERE', timeoutMs: 15000 };
  var keys = { member: 'bpsr.member.session', admin: 'bpsr.admin.session' };
  function configured() { return APP_CONFIG.apiUrl && APP_CONFIG.apiUrl.indexOf('PASTE_') < 0; }
  function safeError(e) { return (e && e.code === 'SESSION_EXPIRED') ? 'Your session has expired. Please sign in again.' : (e && e.message) || 'Request could not be completed.'; }
  function request(action, data) {
    if (!configured()) return Promise.reject(Object.assign(new Error('API URL is not configured. Set APP_CONFIG.apiUrl to the Apps Script /exec URL.'), { code: 'CONFIGURATION' }));
    var controller = typeof AbortController !== 'undefined' ? new AbortController() : null;
    var timer = controller && setTimeout(function () { controller.abort(); }, APP_CONFIG.timeoutMs || 15000);
    return fetch(APP_CONFIG.apiUrl, { method: 'POST', redirect: 'follow', headers: { 'Content-Type': 'text/plain;charset=utf-8' }, body: JSON.stringify({ action: action, data: data || {} }), signal: controller && controller.signal })
      .then(function (r) { return r.text(); }).then(function (text) { var json; try { json = JSON.parse(text); } catch (_) { throw new Error('The API returned an invalid response.'); } if (!json.ok) { var e = new Error((json.error && json.error.message) || 'Request could not be completed.'); e.code = json.error && json.error.code; throw e; } return json.data; })
      .catch(function (e) { if (e.name === 'AbortError') throw new Error('The request timed out. Please try again.'); throw e; })
      .finally(function () { if (timer) clearTimeout(timer); });
  }
  function get(kind) { try { return JSON.parse(localStorage.getItem(keys[kind]) || 'null'); } catch (_) { return null; } }
  function save(kind, session, display) { localStorage.setItem(keys[kind], JSON.stringify({ token: session.token, expiresAt: session.expiresAt, kind: kind, display: display || '' })); }
  function clear(kind) { localStorage.removeItem(keys[kind]); }
  function el(tag, text) { var n = document.createElement(tag); if (text != null) n.textContent = text; return n; }
  function button(text, fn, dangerous) { var b = el('button', text); b.type = 'button'; if (dangerous) b.className = 'ghost'; b.addEventListener('click', function () { b.disabled = true; Promise.resolve(fn()).catch(showError).finally(function () { b.disabled = false; }); }); return b; }
  function showError(e) { var n = document.querySelector('#member-ui .notice') || document.querySelector('#admin-ui .notice'); if (n) { n.className = 'notice error'; n.textContent = safeError(e); } }
  function formField(label, type, name) { var l = el('label', label), i = el('input'); i.type = type; i.name = name; i.required = true; l.htmlFor = name; i.id = name; return [l, i]; }
  function memberUI(profile) { var host = document.getElementById('member-ui'); host.replaceChildren(); var notice = el('div'); notice.className = 'notice'; host.appendChild(notice); if (!profile) { notice.textContent = configured() ? 'Register or sign in to update your own progression.' : 'Configure APP_CONFIG.apiUrl with your Apps Script /exec URL to enable member actions.'; ['Register','Sign in'].forEach(function (mode) { var f = el('form'); f.appendChild(el('h3', mode)); formField('Character name','text','member-name').forEach(function(x){f.appendChild(x);}); formField('PIN (6+ digits)','password','member-pin').forEach(function(x){f.appendChild(x);}); var submit=el('button',mode); submit.type='submit'; f.appendChild(submit); f.addEventListener('submit',function(ev){ev.preventDefault();submit.disabled=true;request(mode==='Register'?'register':'login',{characterName:f.querySelector('[name=member-name]').value,pin:f.querySelector('[name=member-pin]').value}).then(function(r){save('member',r.session,r.member.characterName);memberUI(r.member);}).catch(function(e){notice.className='notice error';notice.textContent=safeError(e);}).finally(function(){submit.disabled=false;});}); host.appendChild(f); }); return; }
    notice.textContent = 'Signed in as '+profile.characterName+'. Totals are calculated by the server.'; var p=el('p','SV floor: '+profile.svFloor+' · Master points: '+profile.masterPoints); host.appendChild(p); var f=el('form'); f.appendChild(el('h3','Update progression')); var sv=el('input');sv.type='number';sv.min='1';sv.max='60';sv.placeholder='SV floor (1–60)'; f.appendChild(sv); var ranks=el('div'); f.appendChild(ranks); request('activities',{}).then(function(a){a.forEach(function(x){var l=el('label',x.name+' (0–'+x.maxRank+')'),i=el('input');i.type='number';i.min='0';i.max=x.maxRank;i.dataset.activity=x.id;i.value=profile.masterRanks[x.id]||0;l.appendChild(i);ranks.appendChild(l);});}); var submit=el('button','Save progression');submit.type='submit';f.appendChild(submit);f.addEventListener('submit',function(ev){ev.preventDefault();var mr={};ranks.querySelectorAll('input').forEach(function(i){mr[i.dataset.activity]=i.value;});submit.disabled=true;request('progress',{token:get('member').token,svFloor:sv.value||undefined,masterRanks:mr}).then(function(r){notice.textContent=r.changed?'Progress updated.':'No genuine progression change.';memberUI(r.profile);if(root.load)root.load();}).catch(function(e){if(e.code==='SESSION_EXPIRED'){clear('member');memberUI();}throw e;}).finally(function(){submit.disabled=false;});});host.appendChild(f);host.appendChild(button('Logout',function(){return request('logout',{token:get('member').token,kind:'member'}).finally(function(){clear('member');memberUI();});},true)); }
  function adminUI() { var host=document.getElementById('admin-ui');host.replaceChildren();var notice=el('div');notice.className='notice';host.appendChild(notice);var s=get('admin');if(!s){notice.textContent='Administrator controls require a separate session.';var f=el('form');formField('Administrator secret','password','admin-secret').forEach(function(x){f.appendChild(x);});var b=el('button','Administrator sign in');f.appendChild(b);f.addEventListener('submit',function(e){e.preventDefault();b.disabled=true;request('adminLogin',{secret:f.querySelector('input').value}).then(function(r){save('admin',r.session,'Administrator');adminUI();}).catch(function(e){notice.className='notice error';notice.textContent=safeError(e);}).finally(function(){b.disabled=false;});});host.appendChild(f);return;} notice.textContent='Administrator session active.';var search=el('input');search.placeholder='Search members';host.appendChild(search);var list=el('div');list.className='member-list';host.appendChild(list);function refresh(){return request('adminMembers',{token:s.token,query:search.value}).then(function(rows){list.replaceChildren();rows.forEach(function(m){list.appendChild(button(m.characterName+' — SV '+m.svFloor,function(){return request('adminRead',{token:s.token,memberId:m.memberId}).then(function(d){notice.textContent=d.characterName+' selected. '+(d.disabled?'Disabled.':'Active.');});}));});});}search.addEventListener('input',refresh);host.appendChild(button('Refresh members',refresh));host.appendChild(button('Find duplicates',function(){return request('adminDuplicates',{token:s.token}).then(function(d){notice.textContent=d.length?'Duplicate groups: '+d.map(function(x){return x.normalizedName;}).join(', '):'No duplicate groups found.';});}));host.appendChild(button('Start manual reset',function(){if(!confirm('Start a new First Guildie period?'))return;return request('adminReset',{token:s.token}).then(function(){notice.textContent='New period started.';if(root.load)root.load();});},true));host.appendChild(button('View audit log',function(){return request('adminAudit',{token:s.token}).then(function(rows){notice.textContent=rows.length?'Latest audit: '+rows[0].action:'No audit records.';});}));host.appendChild(button('Administrator logout',function(){return request('logout',{token:s.token,kind:'admin'}).finally(function(){clear('admin');adminUI();});},true));refresh().catch(function(e){if(e.code==='SESSION_EXPIRED'){clear('admin');adminUI();}else showError(e);});}
  function restore(kind, render) { var s=get(kind); if(!s||!s.token||new Date(s.expiresAt)<=new Date()) {clear(kind);return render(kind==='member'?null:undefined);} request('refresh',{token:s.token,kind:kind}).then(function(){if(kind==='member')return request('me',{token:s.token});}).then(function(p){render(p);}).catch(function(){clear(kind);render(kind==='member'?null:undefined);}); }
  root.BPSR_FRONTEND={request:request,configured:configured,clear:clear,restore:restore}; document.addEventListener('DOMContentLoaded',function(){restore('member',memberUI);restore('admin',adminUI);});
}(window));
