/* Personal two-slot class editor.  Both slots are saved by one API call. */
(function (root) {
  'use strict';
  var CAT = root.BPSR_CLASSES, CONFIG = root.BPSR_CONFIG || {};
  if (!CAT || typeof document === 'undefined') return;
  var state = { selections: [], slots: { primary: null, secondary: null }, loaded: false, open: false, busy: false, error: '', activeTab: 'primary', drafts: { primary: null, secondary: null } };
  var els = {}, lastFocus = null;
  function token() { return root.BPSR_SESSION ? root.BPSR_SESSION.token() : ''; }
  function signedIn() { return Boolean(token()); }
  function configured() { return CONFIG.isConfigured ? CONFIG.isConfigured() : Boolean(CONFIG.apiUrl); }
  function el(tag, cls, text) { var n = document.createElement(tag); if (cls) n.className = cls; if (text != null) n.textContent = text; return n; }
  function cls(id) { return CAT.getClass(id); }
  function buildName(d) { if (!d || !cls(d.classId)) return ''; var b = cls(d.classId).builds.filter(function (x) { return x.id === d.buildId; })[0]; return b ? b.name : ''; }
  function glyph(id, size) { var g = el('span', 'cls-glyph'); g.style.setProperty('--cls-colour', CAT.colourHex(id)); g.style.setProperty('--cls-icon', 'url("' + CAT.iconPath(id) + '")'); if (size) { g.style.width = size + 'px'; g.style.height = size + 'px'; } g.setAttribute('aria-hidden', 'true'); return g; }
  function copy(s) { return s ? { classId: s.classId, buildId: s.buildId } : null; }
  function api(action, data) {
    var controller = new AbortController(), timer = root.setTimeout(function () { controller.abort(); }, CONFIG.timeoutMs || 45000);
    return root.fetch(CONFIG.apiUrl, { method: 'POST', redirect: 'follow', headers: { 'Content-Type': 'text/plain;charset=utf-8' }, body: JSON.stringify({ action: action, data: data }), signal: controller.signal })
      .then(function (r) { return r.text(); }).then(function (text) { var env; try { env = JSON.parse(text); } catch (_) { throw new Error('Invalid response.'); } if (!env.ok) { var e = new Error((env.error || {}).message || 'Request failed.'); e.code = (env.error || {}).code; throw e; } return env.data; })
      .finally(function () { root.clearTimeout(timer); });
  }
  function message(e) { return (e && e.message) || 'Classes could not be saved. Your selections are still here; please try again.'; }
  function ensureTrigger() { if (els.trigger) return; var host = document.getElementById('class-selector'); if (!host) return; var b = el('button', 'cls-trigger'); b.type = 'button'; b.id = 'cls-trigger'; b.setAttribute('aria-haspopup', 'dialog'); b.addEventListener('click', open); host.appendChild(b); els.trigger = b; }
  function renderTrigger() { ensureTrigger(); if (!els.trigger) return; var host = document.getElementById('class-selector'); if (host) host.hidden = !signedIn(); if (!signedIn()) return; var p = state.slots.primary, b = els.trigger; b.replaceChildren(); if (!p) { b.className = 'cls-trigger empty'; b.textContent = state.loaded ? 'Set your classes' : 'Loading…'; b.setAttribute('aria-label', 'Choose your classes'); return; } b.className = 'cls-trigger'; b.appendChild(glyph(p.classId, 26)); var info = el('span', 'cls-trigger-body'); info.appendChild(el('span', 'cls-trigger-name', cls(p.classId).name)); info.appendChild(el('span', 'cls-trigger-build', 'Primary · ' + buildName(p) + (state.slots.secondary ? ' · Secondary: ' + cls(state.slots.secondary.classId).name : ''))); b.appendChild(info); b.setAttribute('aria-label', 'Edit Primary ' + cls(p.classId).name + ' and Secondary class'); }
  function open() { if (!signedIn() || !configured()) return; lastFocus = document.activeElement; state.open = true; state.error = ''; state.activeTab = 'primary'; state.drafts = { primary: copy(state.slots.primary), secondary: copy(state.slots.secondary) }; document.body.classList.add('cls-open'); build(); document.addEventListener('keydown', keys, true); var first = els.modal.querySelector('[role=tab]'); if (first) first.focus(); }
  function close() { state.open = false; document.body.classList.remove('cls-open'); document.removeEventListener('keydown', keys, true); if (els.modal && els.modal.parentNode) els.modal.parentNode.removeChild(els.modal); els.modal = null; if (lastFocus && lastFocus.focus) lastFocus.focus(); }
  function keys(e) { if (e.key === 'Escape') { e.preventDefault(); close(); } }
  function build() { var overlay = el('div', 'cls-modal'); overlay.setAttribute('role', 'presentation'); var dialog = el('section', 'cls-dialog'); dialog.setAttribute('role', 'dialog'); dialog.setAttribute('aria-modal', 'true'); dialog.setAttribute('aria-labelledby', 'cls-dialog-title'); overlay.appendChild(dialog); els.modal = overlay; els.dialog = dialog; document.body.appendChild(overlay); render(); }
  function render() { var d = els.dialog; if (!d) return; d.replaceChildren(); var head = el('div', 'cls-head'); head.appendChild(el('h3', 'cls-title', 'Choose classes')); head.lastChild.id = 'cls-dialog-title'; var x = el('button', 'cls-x', '×'); x.type = 'button'; x.setAttribute('aria-label', 'Close without saving'); x.addEventListener('click', close); head.appendChild(x); d.appendChild(head); if (state.error) { var a = el('p', 'cls-alert', state.error); a.setAttribute('role', 'alert'); d.appendChild(a); }
    var tabs = el('div', 'cls-seg'); tabs.setAttribute('role', 'tablist'); tabs.setAttribute('aria-label', 'Class slot'); ['primary', 'secondary'].forEach(function (slot) { var chosen = state.activeTab === slot, b = el('button', 'cls-seg-btn' + (chosen ? ' on' : ''), slot.toUpperCase()); b.type = 'button'; b.id = 'cls-tab-' + slot; b.setAttribute('role', 'tab'); b.setAttribute('aria-selected', String(chosen)); b.setAttribute('aria-controls', 'cls-panel'); b.addEventListener('click', function () { state.activeTab = slot; state.error = ''; render(); }); tabs.appendChild(b); }); d.appendChild(tabs);
    var summary = el('div', 'cls-slots'); ['primary', 'secondary'].forEach(function (slot) { var item = state.drafts[slot], s = el('div', 'cls-slot ' + slot); s.appendChild(el('strong', slot.toUpperCase())); s.appendChild(el('span', '', item ? cls(item.classId).name + ' · ' + buildName(item) : 'Not selected')); d.appendChild; summary.appendChild(s); }); d.appendChild(summary);
    var panel = el('div', 'cls-body'); panel.id = 'cls-panel'; panel.setAttribute('role', 'tabpanel'); panel.setAttribute('aria-labelledby', 'cls-tab-' + state.activeTab); var draft = state.drafts[state.activeTab]; panel.appendChild(el('p', 'cls-hint', state.activeTab === 'secondary' ? 'Secondary is optional. It must be different from Primary.' : 'Choose your Primary class and build path.'));
    var grid = el('div', 'cls-grid'); grid.setAttribute('role', 'listbox'); grid.setAttribute('aria-label', state.activeTab + ' class'); CAT.catalogue.forEach(function (c) { var duplicate = state.activeTab === 'secondary' && state.drafts.primary && state.drafts.primary.classId === c.id; var selected = draft && draft.classId === c.id; var b = el('button', 'cls-tile' + (selected ? ' on' : '')); b.type = 'button'; b.setAttribute('role', 'option'); b.setAttribute('aria-selected', String(selected)); b.setAttribute('aria-label', c.name + (duplicate ? ', already Primary' : '')); b.disabled = duplicate; b.style.setProperty('--cls-colour', CAT.colourHex(c.id)); b.appendChild(glyph(c.id, 30)); b.appendChild(el('span', 'cls-tile-name', c.name)); b.addEventListener('click', function () { state.drafts[state.activeTab] = { classId: c.id, buildId: c.builds[0].id }; state.error = ''; render(); }); grid.appendChild(b); }); panel.appendChild(grid);
    if (draft && draft.classId) { var builds = el('div', 'cls-builds'); builds.setAttribute('role', 'listbox'); builds.setAttribute('aria-label', 'Build path for ' + cls(draft.classId).name); cls(draft.classId).builds.forEach(function (bld) { var b = el('button', 'cls-build' + (draft.buildId === bld.id ? ' on' : ''), bld.name); b.type = 'button'; b.setAttribute('role', 'option'); b.setAttribute('aria-selected', String(draft.buildId === bld.id)); b.addEventListener('click', function () { state.drafts[state.activeTab].buildId = bld.id; render(); }); builds.appendChild(b); }); panel.appendChild(builds); }
    d.appendChild(panel); var foot = el('div', 'cls-foot'); var cancel = el('button', 'cls-btn ghost', 'Cancel'); cancel.type = 'button'; cancel.addEventListener('click', close); foot.appendChild(cancel); var save = el('button', 'cls-btn primary', state.busy ? 'Saving…' : 'Save classes'); save.type = 'button'; save.disabled = state.busy || !valid(); save.addEventListener('click', saveSlots); foot.appendChild(save); d.appendChild(foot); }
  function valid() { var p = state.drafts.primary, s = state.drafts.secondary; return Boolean(p && CAT.validate(p.classId, p.buildId).ok && (!s || (CAT.validate(s.classId, s.buildId).ok && s.classId !== p.classId))); }
  function saveSlots() { if (state.busy || !valid()) return; state.busy = true; state.error = ''; render(); api('saveClassSlots', { token: token(), primary: state.drafts.primary, secondary: state.drafts.secondary }).then(function (data) { accept(data); state.busy = false; renderTrigger(); close(); if (typeof root.toast === 'function') root.toast('Classes saved.'); }).catch(function (e) { state.busy = false; state.error = message(e); render(); }); }
  function accept(data) { state.selections = data.selections || []; state.slots = data.slots || { primary: state.selections.filter(function (x) { return x.entryType === 'primary'; })[0] || null, secondary: state.selections.filter(function (x) { return x.entryType === 'secondary'; })[0] || null }; }
  function reload() { renderTrigger(); if (!signedIn() || !configured()) { state.loaded = true; return renderTrigger(); } api('myClasses', { token: token() }).then(function (data) { accept(data); state.loaded = true; renderTrigger(); if (state.open) render(); }).catch(function (e) { state.error = message(e); state.loaded = true; renderTrigger(); }); }
  root.CLASS_SELECTOR = { reload: reload, state: state, open: open, close: close };
  document.addEventListener('DOMContentLoaded', function () { renderTrigger(); reload(); });
}(typeof window === 'undefined' ? globalThis : window));
