/* Ordered class/build collection editor. The complete list is saved once. */
(function (root) {
  'use strict';
  var CAT = root.BPSR_CLASSES, CONFIG = root.BPSR_CONFIG || {};
  if (!CAT || typeof document === 'undefined') return;
  var state = { entries: [], drafts: [], picker: null, loaded: false, open: false, busy: false, error: '' };
  var loadInFlight = null, loadGeneration = 0;
  var els = {}, lastFocus = null;
  function token() { return root.BPSR_SESSION ? root.BPSR_SESSION.token() : ''; }
  function signedIn() { return Boolean(token()); }
  function configured() { return CONFIG.isConfigured ? CONFIG.isConfigured() : Boolean(CONFIG.apiUrl); }
  function definitionsReady() { return CAT.ready ? Promise.resolve(CAT) : (root.BPSR_STATIC ? root.BPSR_STATIC.load().then(function () { return CAT; }) : Promise.reject(new Error('Public class definitions are unavailable.'))); }
  function el(tag, cls, text) { var n = document.createElement(tag); if (cls) n.className = cls; if (text != null) n.textContent = text; return n; }
  function classOf(id) { return CAT.getClass(id); }
  function key(x) { return x.classId + '|' + x.buildId; }
  function buildName(x) { var c = x && classOf(x.classId), b = c && c.builds.filter(function (v) { return v.id === x.buildId; })[0]; return b ? b.name : ''; }
  function glyph(id, size) { var g = el('span', 'cls-glyph'); g.style.setProperty('--cls-colour', CAT.colourHex(id)); g.style.setProperty('--cls-icon', 'url("' + CAT.iconPath(id) + '")'); if (size) { g.style.width = size + 'px'; g.style.height = size + 'px'; } g.setAttribute('aria-hidden', 'true'); return g; }
  function allCount() { return CAT.catalogue.reduce(function (n, c) { return n + c.builds.length; }, 0); }
  function api(action, data, retried) { var controller = new AbortController(), timer = root.setTimeout(function () { controller.abort(); }, CONFIG.timeoutMs || 45000); return root.fetch(CONFIG.apiUrl, { method: 'POST', redirect: 'follow', headers: { 'Content-Type': 'text/plain;charset=utf-8' }, body: JSON.stringify({ action: action, data: data }), signal: controller.signal }).then(function (r) { return r.text(); }).then(function (text) { var env; try { env = JSON.parse(text); } catch (_) { throw Object.assign(new Error('The server returned an invalid response.'), { code: 'BAD_RESPONSE' }); } if (!env.ok) { var e = new Error((env.error || {}).message || 'Class saving failed.'); e.code = (env.error || {}).code; throw e; } if (!Object.prototype.hasOwnProperty.call(env, 'data')) { throw Object.assign(new Error('The server returned an incomplete response.'), { code: 'BAD_RESPONSE' }); } return env.data; }).catch(function (failure) { if (!retried && action === 'myClasses' && failure && failure.code === 'BAD_RESPONSE') return api(action, data, true); throw failure; }).finally(function () { root.clearTimeout(timer); }); }
  function describe(e) { if (root.BPSR_ERRORS) return root.BPSR_ERRORS.describe(e, 'classes'); return (e && e.message) || 'Classes could not be saved.'; }
  function ensureTrigger() { if (els.trigger) return; var host = document.getElementById('class-selector'); if (!host) return; var b = el('button', 'cls-trigger'); b.type = 'button'; b.id = 'cls-trigger'; b.setAttribute('aria-haspopup', 'dialog'); b.addEventListener('click', open); host.appendChild(b); els.trigger = b; }
  function renderTrigger() { ensureTrigger(); if (!els.trigger) return; var host = document.getElementById('class-selector'); if (host) host.hidden = !signedIn(); if (!signedIn()) return; var b = els.trigger; b.replaceChildren(); if (!state.entries.length) { b.className = 'cls-trigger empty'; b.textContent = state.loaded ? 'Set your classes' : 'Loading…'; b.setAttribute('aria-label', 'Choose your classes'); return; } b.className = 'cls-trigger'; b.appendChild(glyph(state.entries[0].classId, 26)); var info = el('span', 'cls-trigger-body'); info.appendChild(el('span', 'cls-trigger-name', classOf(state.entries[0].classId).name)); info.appendChild(el('span', 'cls-trigger-build', state.entries.length === 1 ? buildName(state.entries[0]) : state.entries.length + ' saved class builds')); b.appendChild(info); b.setAttribute('aria-label', 'Edit ' + state.entries.length + ' saved class builds'); }
  function open() { if (!signedIn() || !configured()) return; definitionsReady().then(function () { lastFocus = document.activeElement; state.open = true; state.error = ''; state.drafts = state.entries.map(function (x) { return { classId: x.classId, buildId: x.buildId }; }); state.picker = null; document.body.classList.add('cls-open'); var overlay = el('div', 'cls-modal'), dialog = el('section', 'cls-dialog'); dialog.setAttribute('role', 'dialog'); dialog.setAttribute('aria-modal', 'true'); dialog.setAttribute('aria-labelledby', 'cls-dialog-title'); overlay.appendChild(dialog); els.modal = overlay; els.dialog = dialog; document.body.appendChild(overlay); document.addEventListener('keydown', onKey, true); render(); var x = dialog.querySelector('.cls-x'); if (x) x.focus(); }).catch(function (error) { state.error = describe(error); renderTrigger(); }); }
  function close() { state.open = false; document.body.classList.remove('cls-open'); document.removeEventListener('keydown', onKey, true); if (els.modal && els.modal.parentNode) els.modal.parentNode.removeChild(els.modal); els.modal = null; if (lastFocus && lastFocus.focus) lastFocus.focus(); }
  function onKey(e) { if (e.key === 'Escape') { e.preventDefault(); close(); } }
  function pickerValid() { return state.picker && CAT.validate(state.picker.classId, state.picker.buildId).ok && !state.drafts.some(function (x) { return key(x) === key(state.picker); }); }
  function move(from, to) { if (to < 0 || to >= state.drafts.length || from === to) return; var entry = state.drafts.splice(from, 1)[0]; state.drafts.splice(to, 0, entry); state.error = ''; render(); }
  function render() { var d = els.dialog; if (!d) return; d.replaceChildren(); var head = el('div', 'cls-head'); var title = el('h3', 'cls-title', 'Choose classes'); title.id = 'cls-dialog-title'; head.appendChild(title); var x = el('button', 'cls-x', '×'); x.type = 'button'; x.setAttribute('aria-label', 'Close without saving'); x.addEventListener('click', close); head.appendChild(x); d.appendChild(head); if (state.error) { var alert = el('p', 'cls-alert', state.error); alert.setAttribute('role', 'alert'); d.appendChild(alert); }
    var body = el('div', 'cls-body'); body.appendChild(el('p', 'cls-hint', 'Your top class is saved as Primary. Every class below it is saved as Secondary; use Up and Down to set priority.'));
    var list = el('div', 'cls-saved-list'); list.setAttribute('aria-label', 'Classes to save'); if (!state.drafts.length) list.appendChild(el('p', 'cls-hint', 'No classes added yet.')); state.drafts.forEach(function (entry, i) { var c = classOf(entry.classId), row = el('div', 'cls-saved-row'); row.draggable = true; row.dataset.index = i; row.appendChild(el('span', 'cls-drag', '⠿')); row.lastChild.setAttribute('aria-hidden', 'true'); row.appendChild(glyph(entry.classId, 22)); var details = el('span', 'cls-saved-details'); details.appendChild(el('span', 'cls-saved-name', c.name + ' · ' + buildName(entry))); details.appendChild(el('span', 'cls-priority ' + (i === 0 ? 'primary' : 'secondary'), i === 0 ? 'Primary' : 'Secondary')); details.appendChild(el('span', 'cls-role ' + c.roleColor, c.roleLabel)); row.appendChild(details); row.addEventListener('dragstart', function (event) { event.dataTransfer.setData('text/plain', String(i)); event.dataTransfer.effectAllowed = 'move'; }); row.addEventListener('dragover', function (event) { event.preventDefault(); event.dataTransfer.dropEffect = 'move'; }); row.addEventListener('drop', function (event) { event.preventDefault(); move(Number(event.dataTransfer.getData('text/plain')), i); }); var up = el('button', 'cls-mbtn', 'Up'); up.type = 'button'; up.disabled = i === 0; up.setAttribute('aria-label', 'Move ' + c.name + ' ' + buildName(entry) + ' up'); up.addEventListener('click', function () { move(i, i - 1); }); row.appendChild(up); var down = el('button', 'cls-mbtn', 'Down'); down.type = 'button'; down.disabled = i === state.drafts.length - 1; down.setAttribute('aria-label', 'Move ' + c.name + ' ' + buildName(entry) + ' down'); down.addEventListener('click', function () { move(i, i + 1); }); row.appendChild(down); var remove = el('button', 'cls-mbtn danger', 'Remove'); remove.type = 'button'; remove.setAttribute('aria-label', 'Remove ' + c.name + ' ' + buildName(entry)); remove.addEventListener('click', function () { state.drafts.splice(i, 1); state.error = ''; render(); }); row.appendChild(remove); list.appendChild(row); }); body.appendChild(list);
    var exhausted = state.drafts.length >= allCount(); if (exhausted) body.appendChild(el('p', 'cls-hint', 'All available class and build combinations have been added.'));
    if (!exhausted) { var grid = el('div', 'cls-grid'); grid.setAttribute('role', 'listbox'); grid.setAttribute('aria-label', 'Class'); CAT.catalogue.forEach(function (c) { var chosen = state.picker && state.picker.classId === c.id, b = el('button', 'cls-tile' + (chosen ? ' on' : '')); b.type = 'button'; b.setAttribute('role', 'option'); b.setAttribute('aria-selected', String(chosen)); b.style.setProperty('--cls-colour', CAT.colourHex(c.id)); b.appendChild(glyph(c.id, 28)); b.appendChild(el('span', 'cls-tile-name', c.name)); b.addEventListener('click', function () { state.picker = { classId: c.id, buildId: c.builds[0].id }; state.error = ''; render(); }); grid.appendChild(b); }); body.appendChild(grid);
      if (state.picker) { var builds = el('div', 'cls-builds'); builds.setAttribute('role', 'listbox'); builds.setAttribute('aria-label', 'Build path for ' + classOf(state.picker.classId).name); classOf(state.picker.classId).builds.forEach(function (build) { var b = el('button', 'cls-build' + (state.picker.buildId === build.id ? ' on' : ''), build.name); b.type = 'button'; b.setAttribute('role', 'option'); b.setAttribute('aria-selected', String(state.picker.buildId === build.id)); b.addEventListener('click', function () { state.picker.buildId = build.id; state.error = ''; render(); }); builds.appendChild(b); }); body.appendChild(builds); }
      var add = el('button', 'cls-btn add', '+ Add class'); add.type = 'button'; add.disabled = !pickerValid(); if (!state.picker) add.title = 'Choose a class and build path first.'; else if (!pickerValid()) add.title = 'That class and build is already in your list.'; add.addEventListener('click', function () { if (!pickerValid()) { state.error = state.picker ? 'That class and build is already in your list.' : 'Choose a class and build path first.'; render(); return; } state.drafts.push({ classId: state.picker.classId, buildId: state.picker.buildId }); state.picker = null; state.error = ''; render(); }); body.appendChild(add); }
    d.appendChild(body); var foot = el('div', 'cls-foot'); var cancel = el('button', 'cls-btn ghost', 'Cancel'); cancel.type = 'button'; cancel.addEventListener('click', close); foot.appendChild(cancel); var save = el('button', 'cls-btn primary', state.busy ? 'Saving…' : 'Save classes'); save.type = 'button'; save.disabled = state.busy; save.addEventListener('click', saveAll); foot.appendChild(save); d.appendChild(foot); }
  function saveAll() { if (state.busy) return; state.busy = true; state.error = ''; render(); api('saveClasses', { token: token(), entries: state.drafts.map(function (entry, i) { return { classId: entry.classId, buildId: entry.buildId, entryType: i === 0 ? 'primary' : 'secondary' }; }) }).then(function (data) { accept(data); state.busy = false; renderTrigger(); close(); if (typeof root.toast === 'function') root.toast('Classes saved.'); }).catch(function (e) { state.busy = false; state.error = describe(e); render(); }); }
  function accept(data) { state.entries = (data.entries || data.selections || []).map(function (x) { return { classId: x.classId, buildId: x.buildId }; }); }
  function reload(force) {
    renderTrigger();
    if (!signedIn() || !configured()) { state.loaded = true; renderTrigger(); return Promise.resolve(null); }
    if (loadInFlight) return loadInFlight;
    if (state.loaded && !force) return Promise.resolve(state.entries);
    var generation = ++loadGeneration;
    loadInFlight = definitionsReady().then(function () { return api('myClasses', { token: token() }); }).then(function (data) {
      if (generation !== loadGeneration) return null;
      accept(data); state.loaded = true; state.error = ''; renderTrigger(); if (state.open) render();
      return state.entries;
    }).catch(function (e) {
      if (generation !== loadGeneration) return null;
      state.error = describe(e); state.loaded = true; renderTrigger();
      return null;
    }).finally(function () { if (generation === loadGeneration) loadInFlight = null; });
    return loadInFlight;
  }
  function reset() {
    loadGeneration++; loadInFlight = null; state.entries = []; state.drafts = [];
    state.loaded = false; state.error = ''; renderTrigger();
  }
  root.CLASS_SELECTOR = { reload: reload, reset: reset, sync: renderTrigger, state: state, open: open, close: close };
  document.addEventListener('DOMContentLoaded', renderTrigger);
}(typeof window === 'undefined' ? globalThis : window));
